### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/mosra/corrade/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/mosra/corrade).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by mosra** [comment]
Hi! I browsed through the reports and I have a few questions to which I wasn't able to find an answer in the help:

- how are the checks done? is this some sort of static analysis done by compiling the C++ code and running the tests? if so, how does it know how to compile the code and what to run? if not, is there some overview of what it checks for?
- how often are the checks done? for example right now I pushed a fix to those three reports, but nothing in the repo page indicates that it's waiting for new data or that there's new commits, I also wasn't able to find any way to manually trigger a re-check
- how is the language detection done and how can I override it? For example for https://lgtm.com/projects/g/mosra/magnum it says "JavaScript", but there's like 70 lines of JavaScript and the rest 200k lines are C++.

Thanks!

**Comment by xcorail** [comment]
Hi @mosra 

> is this some sort of static analysis done by compiling the C++ code and running the tests?

Yes, we [compile](https://lgtm.com/help/lgtm/analysis-faqs#why-bother-compiling-code) the code, generate a DB out of it, that we can query later thanks to an object oriented query language. This allows us to modify and adapt very quickly [these analyses](https://github.com/Semmle/ql) in case a false positive is found. You can find there the exhaustive list of queries that are run for [cpp](https://github.com/Semmle/ql/tree/master/cpp)

> how does it know how to compile the code and what to run?

LGTM tries to auto-build your code. While it can be easy for some languages, it can be tricky for others. When our auto-build fails, there is a way to let you tell LGTM what to build and what to run by [customizing the extraction process](https://lgtm.com/help/lgtm/cpp-extraction). Don't hesitate to ping us for help, on this specific matter!  

> how often are the checks done?

LGTM analyses all commits: https://lgtm.com/help/lgtm/analysis-faqs#code-base-v-commit
We give priority to pull request integration, then all commits, starting with most recent. No need to trigger, but your result will take some time to appear if there are many PR that are being analysed at the moment. BTW, I recommend you to activate PR integration [here](https://lgtm.com/projects/g/mosra/corrade/ci/). LGTM will report any new problem (or fix) directly within the PR. Give it a try and let me know

> how is the language detection done and how can I override it? 

This is [how](https://lgtm.com/help/lgtm/analysis-faqs#how-does-lgtm-determine-which-languages-to-analyze). If C++ does not appear, it's certainly because the autobuild failed to compile this code. So you are left with the JavaScript.  Let me ping our support team about the C++ build for this project and get back to you. 
When the C++ compilation succeeds, you will be able to decide to disregard the JavaScript code just by excluding these files from your scope, in a `.lgtm.yml` file like this
```
path_classifiers:
  documentation:
    - **/*.js
```

**Comment by mosra** [comment]
Ah, thanks, the [.lgtm.yml](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file) file was exactly what I was looking for. The project at https://lgtm.com/projects/g/mosra/magnum depends on this project, corrade, so that's probably why the build failed -- basically, I would need to mirror the [build scripts I have for Travis](https://github.com/mosra/magnum/tree/master/package/ci) in order to have everything built correctly.

That's a non-trivial amount of work, so once I get some free time, I'll look into this more deeply. Curious what it finds for the other projects.

Thanks for the help so far!

**Comment by xcorail** [comment]
@mosra give us a shout when you find time looking into this. If we are available at that moment we'll be happy to help

**Comment by xcorail** [comment]
Some help for once you find time to work on it : My colleagues had a quick look and it appears that during the build process of `mosra/magnum`, it tries to do a `git clone` of the `mosra/corrade` project. That's not supported. The proper way to set such a thing up in `mosra/magnum` is by making `mosra/corrade` a Git submodule of `magnum`. That is something that we do support.

**Comment by mosra** [comment]
Ah, I see, Unfortunately this is already a well-established project and it's not possible to do such changes to it without breaking things for existing users...

As a workaround, do you support downloading files via `wget`, for example? Besides this direct dependency there is a lot of other 3rd party software the libraries (optionally) depend on (and some of these are either heavily outdated in Ubuntu repos or not available there at all, so I can't just `apt install`).

**Comment by sjvs** [comment]
Hi @mosra! I'll reply on behalf of @xcorail. LGTM does indeed allow `wget` and will automatically cache repeated requests. That's handy for historical analysis, where the same versions of dependencies are downloaded over and over again. However, it does mean that just downloading `https://github.com/mosra/corrade/archive/master.zip` probably won't work: the zip file will be cached in the proxy.

Of course it will work if you rely on particular versions of dependencies, and do `wget https://github.com/mosra/corrade/archive/2be9e55a06bcae5e085d33b6af3ec8e9d55e89c4.zip`. However, at that stage you have more or less reinvented Git submodules :slightly_smiling_face:.

On a side-note: LGTM will automatically `apt-get install` all of your dependencies in almost all situations. Here's some background info: https://lgtm.com/blog/how_lgtm_builds_cplusplus

Note that it doesn't have to be difficult to start using submodules for `corrade` and `magnum` — indeed, you already use them for the `toolchains` directory. I don't think it'd break things for many (if any) people: you'd have to replace the `git clone` by a `git submodule update --init` and the rest will happen automagically. It'd also have the added advantage of having a stronger version coupling between `corrade` and `magnum`: if you ever wanted to build an older version of `magnum`, it'd automatically fetch the compatible (older) version of `corrade`. At the moment, historical builds probably don't work: older version of `magnum` still pull in the most recent `master` of `corrade`, which may well be incompatible.

**Comment by mosra** [comment]
Hmm. I think I could work around this using some cache busting thing (`https://github.com/mosra/corrade/archive/master.zip?bla=1536075193` seems to work, for example). The proxy cache should not conflate all these into a single file, right?

> Note that it doesn't have to be difficult to start using submodules for `corrade` and `magnum` [...]

I'm *very* aware of all the pros and cons of submodules, trust me ;) Used them for a larger project back in 2008-2010 and the overhead of updating the submodule HEAD in basically every second commit was outweighing any potential advantages of having pinned versions of dependencies. Besides that, I have other projects that depend on magnum, which means there would be a recursive submodule chain and that doesn't look like a good thing to have.

**Comment by sjvs** [comment]
> Hmm. I think I could work around this using some cache busting thing 
That may well work, indeed.

> I'm very aware of all the pros and cons of submodules, trust me ;) [...]
Hehe. I know exactly what you mean :).

**Comment by sjvs** [comment]
It turned that `travis-desktop.sh` was almost exactly right for an LGTM.com build script for `magnum`. I've opened a PR: https://github.com/mosra/magnum/pull/280

**Comment by xcorail** [comment]
Hey @mosra 

Just wanted to let you know that during 6 weeks, for each LGTM alert fixed, we'll make a donation to WWF. You can also win a free ticket to GitHub Universe, with travel and accommodation. Details here: https://competitions.lgtm.com/ghu-2018

**Comment by mosra** [comment]
I decided to not go further with this, see https://github.com/mosra/magnum/pull/280 for details.

**Pull request closed without merging**
